export type Player={name:string;power:number};export type Assignment={building:string;emoji:string;leader:string;players:string};export type Plan={p1:Assignment[];p23:Assignment[];p4:Assignment[];final5:Assignment[]};
const emoji:any={"Prototype 1":"💛","Prototype 2":"🔴","Repair 1":"🍊","Repair 2":"💚","Repair 3":"🩵","Repair 4":"💙","Boiler":"💛","Boiler from P1":"💛","Transit":"💗","Middle":"🔴","Munition":"💚","Munitions":"🔴","Workshop NW":"💜","Workshop NE":"💙","Workshop SE":"💗","Workshop SW":"🩵","R1":"🍊","R2":"💚","R3":"🩵","R4":"💙","P2":"🔴"};
const p1Buildings=["Prototype 1","Prototype 2","Repair 1","Repair 2","Repair 3","Repair 4","Boiler","Transit"];const p1Remainder=["Repair 1","Repair 2","Repair 3","Repair 4","Boiler","Transit"];
export function parsePlayers(raw:string):Player[]{return raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const tab=line.split(/\t+/).map(x=>x.trim()).filter(Boolean);if(tab.length>=2&&/^\d+(\.\d+)?$/.test(tab[tab.length-1]))return{name:tab.slice(0,-1).join(' '),power:Number(tab[tab.length-1])};const comma=line.split(',').map(x=>x.trim()).filter(Boolean);if(comma.length>=2&&/^\d+(\.\d+)?$/.test(comma[comma.length-1]))return{name:comma.slice(0,-1).join(', '),power:Number(comma[comma.length-1])};const m=line.match(/^(.*?)\s+([0-9]+(?:\.[0-9]+)?)$/);return m?{name:m[1].trim(),power:Number(m[2])}:null}).filter(Boolean).sort((a:any,b:any)=>b.power-a.power) as Player[]}
function mk(building:string,leader?:string,team:Player[]=[]):Assignment{return{building,emoji:emoji[building]||'•',leader:leader||'TBC',players:team.length?team.map(p=>p.name).join(', '):'TBC'}}
function pow(players:Player[],name:string){return players.find(p=>p.name===name)?.power||0}function split(text:string){return String(text||'').split(/,|\//).map(x=>x.trim()).filter(Boolean).filter(x=>x!=='TBC'&&!x.includes('(from P1)'))}
function balance(list:Player[],buckets:number){const arr=Array.from({length:buckets},()=>({players:[] as Player[],power:0}));list.forEach(p=>{arr.sort((a,b)=>a.power-b.power||a.players.length-b.players.length);arr[0].players.push(p);arr[0].power+=p.power});return arr}
function buildP1(players:Player[]){const rows=p1Buildings.map((b,i)=>({building:b,leader:players[i],team:[] as Player[],total:players[i]?.power||0}));const sp=balance(players.slice(8,16),2);rows[0].team=sp[0].players;rows[0].total+=sp[0].power;rows[1].team=sp[1].players;rows[1].total+=sp[1].power;players.slice(16).forEach(p=>{const c=rows.filter(r=>p1Remainder.includes(r.building));c.sort((a,b)=>a.total-b.total||a.team.length-b.team.length);c[0].team.push(p);c[0].total+=p.power});return rows.map(r=>mk(r.building,r.leader?.name,r.team))}
function lead(p1:Assignment[],building:string){return p1.find(r=>r.building===building)?.leader||'TBC'}
function buildP23(players:Player[],p1:Assignment[]){const transitions=[["Middle","Prototype 1"],["Prototype 1","Prototype 2"],["Repair 1","Repair 1"],["Munition","Repair 2"],["Workshop SW","Repair 3"],["Workshop NE","Repair 4"],["Workshop NW","Boiler"],["Workshop SE","Transit"]];const rows=transitions.map(([target,source])=>({building:target,leader:lead(p1,source),team:[] as Player[],total:pow(players,lead(p1,source))}));const by:any=Object.fromEntries(rows.map(r=>[r.building,r]));const leadNames=new Set(rows.map(r=>r.leader).filter(x=>x&&x!=='TBC'));const non=players.filter(p=>!leadNames.has(p.name));non.slice(0,6).forEach(p=>{const t=by.Middle.total<=by['Prototype 1'].total?by.Middle:by['Prototype 1'];t.team.push(p);t.total+=p.power});non.slice(6,9).forEach(p=>{by['Repair 1'].team.push(p);by['Repair 1'].total+=p.power});non.slice(9,12).forEach(p=>{by.Munition.team.push(p);by.Munition.total+=p.power});const ws=[by['Workshop NW'],by['Workshop NE'],by['Workshop SE'],by['Workshop SW']];non.slice(12,20).forEach(p=>{const c=ws.filter(w=>w.team.length<2);c.sort((a,b)=>a.total-b.total||a.team.length-b.team.length);const t=c[0]||ws[0];t.team.push(p);t.total+=p.power});non.slice(20).forEach(p=>{const t=by.Middle.total<=by['Prototype 1'].total?by.Middle:by['Prototype 1'];t.team.push(p);t.total+=p.power});return ['Middle','Prototype 1','Repair 1','Munition','Workshop NW','Workshop NE','Workshop SE','Workshop SW'].map(b=>mk(b,by[b].leader,by[b].team))}
const positions:any={Middle:[50,50],'Prototype 1':[20,40],'Prototype 2':[80,62],'Boiler from P1':[32,14],Boiler:[32,14],R1:[14,54],R2:[86,48],R3:[30,86],R4:[64,14],Munitions:[50,72],Munition:[50,72],'Workshop NW':[30,27],'Workshop NE':[66,27],'Workshop SE':[70,70],'Workshop SW':[30,70]};
function find(rows:Assignment[],b:string){return rows.find(r=>r.building===b)||mk(b)}function dist(a:string,b:string){const pa=positions[a]||[50,50],pb=positions[b]||[50,50];return Math.hypot(pa[0]-pb[0],pa[1]-pb[1])}function prevMap(p23:Assignment[]){const m=new Map<string,string>();p23.forEach(r=>[...split(r.leader),...split(r.players)].forEach(n=>m.set(n,r.building)));return m}
function buildP4(players:Player[],p23:Assignment[]){const a1=players.find(p=>p.name===find(p23,'Middle').leader)||players[0];const a2=players.find(p=>p.name===find(p23,'Prototype 1').leader)||players[1];const reserved=new Set([a1?.name,a2?.name].filter(Boolean));const second=players.filter(p=>!reserved.has(p.name)).slice(0,7);second.forEach(p=>reserved.add(p.name));const prev=prevMap(p23);const teams=[{building:'Prototype 1',leader:`${a1?.name||'TBC'}/${second[0]?.name||'TBC'}`,team:[] as Player[],total:(a1?.power||0)+(second[0]?.power||0)},{building:'Boiler from P1',leader:`${a1?.name||'TBC'} (from P1)`,team:[] as Player[],total:(a1?.power||0)},{building:'R4',leader:`${a1?.name||'TBC'}/${second[5]?.name||'TBC'}`,team:[] as Player[],total:(a1?.power||0)+(second[5]?.power||0)},{building:'R1',leader:`${a1?.name||'TBC'}/${second[2]?.name||'TBC'}`,team:[] as Player[],total:(a1?.power||0)+(second[2]?.power||0)},{building:'P2',leader:`${a2?.name||'TBC'}/${second[6]?.name||'TBC'}`,team:[] as Player[],total:(a2?.power||0)+(second[6]?.power||0)},{building:'Munitions',leader:`${a2?.name||'TBC'}/${second[1]?.name||'TBC'}`,team:[] as Player[],total:(a2?.power||0)+(second[1]?.power||0)},{building:'R3',leader:`${a2?.name||'TBC'}/${second[4]?.name||'TBC'}`,team:[] as Player[],total:(a2?.power||0)+(second[4]?.power||0)},{building:'R2',leader:`${a2?.name||'TBC'}/${second[3]?.name||'TBC'}`,team:[] as Player[],total:(a2?.power||0)+(second[3]?.power||0)}];players.filter(p=>!reserved.has(p.name)).forEach(p=>{const old=prev.get(p.name)||'Middle';teams.sort((a,b)=>dist(old,a.building)-dist(old,b.building)||a.total-b.total);teams[0].team.push(p);teams[0].total+=p.power});return teams.map(t=>mk(t.building,t.leader,t.team))}
function buildFinal(players:Player[]){return[mk('Middle',`${players[0]?.name||'TBC'}/${players[1]?.name||'TBC'}/${players[2]?.name||'TBC'}/${players[3]?.name||'TBC'}`,players.slice(4,16))]}
export function buildPlan(raw:string){const players=parsePlayers(raw);const p1=buildP1(players);const p23=buildP23(players,p1);const p4=buildP4(players,p23);const final5=buildFinal(players);return{players,plan:{p1,p23,p4,final5}}}
export function line(r:Assignment){return`${r.emoji} ${r.building}: ${r.leader} - ${r.players}`}export function block(rows:Assignment[]){return rows.map(line).join('\n')}export function discordOutput(title:string,plan:Plan){return`🔥 **${title}**\n\n**PHASE 1**\n${block(plan.p1)}\n\n**PHASE 2-3**\n${block(plan.p23)}\n\n**PHASE 4**\n${block(plan.p4)}\n\n**FINAL 5**\n${block(plan.final5)}\n\nNo freelancing. Fill rallies first.`}
